### PR TITLE
8254569: Remove hard dependency on Dispman in Monocle fb rendering

### PR DESCRIPTION
**Pull request by johanvos**
Allow the EGL functionality in monocle to leverage EGL-based systems. The low-level specific details about how the EGL calls should be constructed are left out, and a native interface (egl_ext.h) is created that can be mapped to any low-level system.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8254569](https://bugs.openjdk.java.net/browse/JDK-8254569): Remove hard dependency on Dispman in Monocle fb rendering

### Reviewers
 * [Kevin Rushforth](https://openjdk.java.net/census#kcr) (@kevinrushforth - **Reviewer**)
 * [Jose Pereda](https://openjdk.java.net/census#jpereda) (@jperedadnr - Committer)

### Download
`$ git fetch https://git.openjdk.java.net/jfx pull/343/head:pull/343`
`$ git checkout pull/343`

### CODE REVIEW

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+    private long eglWindowHandle = -1;
+
+    /**
+     * Create a new <code>EGLAcceleratedScreen</code> with a set of attributes.
+     * This will create an <code>EGL Context</code> that can be used by the
+     * Prism component.
+     * @param attributes an array of attributes that will be used by the underlying
+     *        implementation to get the best matching configuration.
+     */
+    EGLAcceleratedScreen(int[] attributes) throws GLException {
```
Comment (kevinrushforth) [inline modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java:45]: I presume you intended to call the (newly added) default `super` method and not `super(int[])`?

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLPlatform.java [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+
+    /**
+     * Create an <code>EGLPlatform</code>. If a library with specific native code is needed for this platform,
+     * it will be downloaded now. The system property <code>monocle.egl.lib</code> can be used to define the
+     * name of the library that should be loaded.
+     */
+    public EGLPlatform() {
+        String lib = System.getProperty("monocle.egl.lib");
+        if (lib != null) {
+            LinuxSystem.getLinuxSystem().dlopen(lib, LinuxSystem.RTLD_LAZY | LinuxSystem.RTLD_GLOBAL);
```
Comment (kevinrushforth) [inline modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLPlatform.java:37]: Do you need to check the return value (and maybe throw an Exception)?

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLPlatform.java [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+        }
+    }
+
+    @Override
+    public synchronized AcceleratedScreen getAcceleratedScreen(int[] attributes) throws GLException {
+        return new EGLAcceleratedScreen(attributes);
```
Comment (kevinrushforth) [inline modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLPlatform.java:43]: Should this method cache the result so it returns a singleton (not sure, but the other `NativePlatform` subclasses, including `Dispman` do)?

File: modules/javafx.graphics/src/main/native-glass/monocle/egl/eglBridge.c [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+
+JNIEXPORT jboolean JNICALL Java_com_sun_glass_ui_monocle_EGLAcceleratedScreen_nEglBindApi
+    (JNIEnv *env, jclass clazz, jint api) {
+    jboolean answer = doEglBindApi((int)api);
+    return answer;
+}
+
+JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_EGLAcceleratedScreen_nEglChooseConfig
+    (JNIEnv *env, jclass clazz, jlong eglDisplay, jintArray attribs) {
+    jint *attrArray = (*env)->GetIntArrayElements(env, attribs, JNI_FALSE);
```
Comment (kevinrushforth) [inline modules/javafx.graphics/src/main/native-glass/monocle/egl/eglBridge.c:56]: Should this check the return value in case it fails (returns NULL)?

File: modules/javafx.graphics/src/main/native-glass/monocle/egl/egl_ext.h [hunk 5]
```diff
@@ -0,0 +1,16 @@
+#include <jni.h>
```
Comment (kevinrushforth) [inline modules/javafx.graphics/src/main/native-glass/monocle/egl/egl_ext.h:1]: This needs a standard copyright header.

Also should it have a guard to prevent including it more than once?

**Review by kevinrushforth — COMMENTED** [review]
Looks OK as near as I can tell. I left a few questions along with a comment about a missing copyright header (that's the only thing that definitely needs to be fixed).

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLPlatform.java (hunk 2 above)
Comment (johanvos) [reply modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLPlatform.java:37]: Good idea. Added.

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLPlatform.java (hunk 3 above)
Comment (johanvos) [reply modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLPlatform.java:43]: Good question. In theory (e.g. on the Pi 4), there can be 2 different hardware accelerated screens, but their is no application logic in the higher layers for distributing rendering to 2 different interfaces. 
Hence, it is indeed better to cache the result.

File: modules/javafx.graphics/src/main/native-glass/monocle/egl/eglBridge.c (hunk 4 above)
Comment (johanvos) [reply modules/javafx.graphics/src/main/native-glass/monocle/egl/eglBridge.c:56]: I checked other places in the code, and calls to env->GetIntArrayElements are typically not checked.
However, if something fails in that call, it must be something really bad that happened. I added a fprintf to stderr, and throw an IllegalArgumentException in the java code (as there is something wrong with the attribs)

File: modules/javafx.graphics/src/main/native-glass/monocle/egl/egl_ext.h (hunk 5 above)
Comment (johanvos) [reply modules/javafx.graphics/src/main/native-glass/monocle/egl/egl_ext.h:27]: correct. fixed.

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java (hunk 1 above)
Comment (johanvos) [reply modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java:45]: Yes, this will (implicitly) call the super() method instead of the super(int[] ) method. The problem with the latter (and actually the reason for this approach) is that the flow in the super(int[]) constructor is very specific to specific use-cases, and would require subclasses for every EGL-system that does not behave 100% similar to the specific usecase.

**Review by kevinrushforth — APPROVED** [review]
Looks good.

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+        eglContext = nEglCreateContext(eglDisplay, eglConfig);
+    }
+
+    @Override
+    protected long platformGetNativeWindow() {
+        String displayID = System.getProperty("egl.displayid", "/dev/dri/card1" );
+        return nPlatformGetNativeWindow(displayID);
+    }
+
+    public void enableRendering(boolean flag) {
```
Comment (jperedadnr) [inline modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java:64]: Add `@Override` annotation

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+            nEglMakeCurrent(eglDisplay, eglSurface, eglSurface,
+                                       eglContext);
+        } else {
+            nEglMakeCurrent(eglDisplay, 0, 0, eglContext);
+        }
+    }
+
+    public boolean swapBuffers() {
+        boolean result = false;
+        synchronized(NativeScreen.framebufferSwapLock) {
```
[the remark this answers is not in the document]
Comment (johanvos) [reply modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java]: fixed

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java (hunk 6 above)
Comment (johanvos) [reply modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java:65]: done

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+    public void enableRendering(boolean flag) {
+        if (flag) {
+            nEglMakeCurrent(eglDisplay, eglSurface, eglSurface,
+                                       eglContext);
+        } else {
+            nEglMakeCurrent(eglDisplay, 0, 0, eglContext);
+        }
+    }
+
+    public boolean swapBuffers() {
```
[the remark this answers is not in the document]
Comment (johanvos) [reply modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java:75]: Indeed, I added it.

**Review by jperedadnr — APPROVED** [review]

**Review by kevinrushforth — APPROVED** [review]

**Review by jgneff — COMMENTED** [review]
I wanted to put the EGL bridge into a library called `libglass_monocle_egl.so` built by JavaFX, as we do for X11 and EPD, and then simply drop the custom library that implements `egl_ext.h` into the same directory. Yet I was unable to get `glass_monocle_egl` to resolve the symbols in my custom library at runtime, even when both were loaded successfully.

I ended up having to build the bridge and custom implementation into one shared library. So instead of just the `egl_ext.h` header file and my `test01.c` source file, I required all of the following:

```
com_sun_glass_ui_monocle_EGLAcceleratedScreen.h
Monocle.h
egl_ext.h
eglBridge.c
test01.c
```

I thought it would be nice to build and load them separately, but I haven't been able to figure it out. The code change would be something like the following:

**EGLPlatform.java**
```java
import com.sun.glass.utils.NativeLibLoader;

public EGLPlatform() {
    String lib = System.getProperty("monocle.egl.lib");
    if (lib != null) {
        NativeLibLoader.loadLibrary(lib);
    }
    NativeLibLoader.loadLibrary("glass_monocle_egl");
}
```

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLPlatform.java [hunk 9]
```diff
@@ -0,0 +1,53 @@
...
+     */
+    public EGLPlatform() {
+        String lib = System.getProperty("monocle.egl.lib");
+        if (lib != null) {
+            long handle = LinuxSystem.getLinuxSystem().dlopen(lib, LinuxSystem.RTLD_LAZY | LinuxSystem.RTLD_GLOBAL);
+            if (handle == 0) {
+                throw new UnsatisfiedLinkError("EGLPlatform failed to load the requested library " + lib);
+            }
+        }
+    }
```
[the remark this answers is not in the document]
Comment (johanvos) [reply modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLPlatform.java:42]: The difference between how I'm building it and how you are building is that I combine all monocle code in 1 library (libglass_monocle.so) where you have a common monocle library and a egl-specific one -- and this is what you do with the EPD as well. For Android, we use a single library as well. At build time, the android-specific classes are added in libglass_monocle.so and dlopen() is used to load android-specific libraries at runtime.

Both approaches are valid, but can't be mixed. Hence we need to decide to either go for 1 or 2 monocle libraries (the android approach, where there is libglass_monocle only or the epd approach where there is also libglass_monocle_epd). I don't have a strong preference, but I think libglass_monocle will be really very small.

Bundling the device-specific library (in your case the one containing test01.o) with the monocle library (the general or a specific one) seems less interesting, as that means you need e.g. 4 different monocle libraries for 4 different Pi-configurations. I believe it is better to share the monocle libraries, and have a single OpenJFX library for monocle, and then platform/configuration-specific libraries.

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java [hunk 10]
```diff
@@ -0,0 +1,92 @@
...
+
+    /**
+     * Create a new <code>EGLAcceleratedScreen</code> with a set of attributes.
+     * This will create an <code>EGL Context</code> that can be used by the
+     * Prism component.
+     * @param attributes an array of attributes that will be used by the underlying
+     *        implementation to get the best matching configuration.
+     */
+    EGLAcceleratedScreen(int[] attributes) throws GLException {
+        eglWindowHandle = platformGetNativeWindow();
```
[the remark this answers is not in the document]
Comment (johanvos) [reply modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java:46]: We can make this private, but that would give a wrong sense of security, as the native method can still be implemented in different ways.
@kevinrushforth Do we have the policy of not using overridable method calls in constructors?

File: modules/javafx.graphics/src/main/native-glass/monocle/egl/egl_ext.h [hunk 11]
```diff
@@ -0,0 +1,43 @@
...
+ *
+ * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
+ * or visit www.oracle.com if you need additional information or have any
+ * questions.
+ */
+#ifndef __EGL_EXT__
+#define __EGL_EXT__
+#include <jni.h>
+extern long getNativeWindowHandle(const char *v);
+extern long getEGLDisplayHandle();
```
[the remark this answers is not in the document]
Comment (johanvos) [reply modules/javafx.graphics/src/main/native-glass/monocle/egl/egl_ext.h]: fixed.

File: modules/javafx.graphics/src/main/native-glass/monocle/egl/egl_ext.h [hunk 12]
```diff
@@ -0,0 +1,43 @@
...
+extern jboolean doEglInitialize(void* handle);
+extern jboolean doEglBindApi(int api);
+extern jlong doEglChooseConfig (long eglDisplay, int* attribs);
```
[the remark this answers is not in the document]
Comment (johanvos) [reply modules/javafx.graphics/src/main/native-glass/monocle/egl/egl_ext.h]: fixed

File: modules/javafx.graphics/src/main/native-glass/monocle/egl/egl_ext.h [hunk 13]
```diff
@@ -0,0 +1,43 @@
...
+
+extern jlong doEglCreateWindowSurface (jlong eglDisplay, jlong config,
+     jlong nativeWindow);
+
+extern jlong doEglCreateContext (jlong eglDisplay, jlong config);
+
+extern jboolean doEglMakeCurrent (jlong eglDisplay, jlong drawSurface,
+     jlong readSurface, jlong eglContext);
+
+extern jboolean doEglSwapBuffers(jlong eglDisplay, jlong eglSurface);
```
[the remark this answers is not in the document]
Comment (johanvos) [reply modules/javafx.graphics/src/main/native-glass/monocle/egl/egl_ext.h:42]: Initially, I wanted to avoid jni.h in this external file. However, since 2 of the functions return a boolean value, I introduced jboolean, but didn't change all values. 
We can still go back to the non-jni types, e.g. by having an int instead of a jboolean, but at this moment I think the presence of jni.h should not be a showstopper. 
Implementations of this interface will be (or bundled with) code that does not know about Java, hence I tried to avoid jni types, but in case jni.h is not available, the implementation can easily typedef the required types.

I made it consistent now to use jlong instead of long.

File: modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (kevinrushforth) [reply modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/EGLAcceleratedScreen.java:46]: We do this in other places as well. It needs to be considered carefully, but in this case seems reasonable to do as long as the subclass doesn't rely on anything initialized in its constructor.

**Review by kevinrushforth — APPROVED** [review]

**Review by jperedadnr — APPROVED** [review]

**Comment by jgneff** [comment]
The fix for the compile-time error still fails for target *armv6hf*: `MonocleGLFactory.c:110:19: error: ‘RTLD_DEFAULT’ undeclared (first use in this function)`. Here's one solution:

```diff
--- a/modules/javafx.graphics/src/main/native-prism-es2/monocle/MonocleGLFactory.c
+++ b/modules/javafx.graphics/src/main/native-prism-es2/monocle/MonocleGLFactory.c
@@ -29,16 +29,13 @@
 #include <string.h>
 #include <math.h>
 
+#ifndef ANDROID_NDK
+#define __USE_GNU
+#endif
 #include <EGL/egl.h>
 #include "eglUtils.h"
 
-#include "../PrismES2Defs.h"
-
 #include "com_sun_prism_es2_MonocleGLContext.h"
-#ifndef ANDROID
-#define __USE_GNU
-#include <dlfcn.h>
-#endif
 
 extern void *get_dlsym(void *handle, const char *symbol, int warn);
  ```

Turns out `eglUtils.h` already includes `../PrismES2Defs.h`, which also includes `<dlfcn.h>` and defines `__USE_GNU` if it's not already defined.

I'm still trying to understand why we need to define `__USE_GNU` ahead of time right at the top there. I'll add another comment if I figure it out.

**Comment by johanvos** [comment]
That sounds like an issue with your toolchain. RTLD_DEFAULT is not standard posix, but the toolchain should detect to use GNU_SOURCE. Maybe you can specify it to the compiler?

**Review by kevinrushforth — APPROVED** [review]

**Comment by jgneff** [comment]
Thanks, Johan. Can we compare build environments? I cross-compile on Ubuntu 20.04.1 LTS. I followed the instructions at [Cross Building for ARM Hard Float][1] to fetch the toolchain. I use OpenJDK 14.0.2, Ant 1.10.7, and Gradle 6.3, by sourcing this script:

```Shell
# Sets up the environment for building JavaFX
syspath=/usr/sbin:/usr/bin:/sbin:/bin

export JAVA_HOME=/usr/lib/jvm/java-14-openjdk-amd64
export ANT_HOME=/usr/share/ant
export GRADLE_HOME=$HOME/opt/gradle-6.3

# JDK_HOME and PATH are required by the build
export JDK_HOME=$JAVA_HOME
export PATH=$GRADLE_HOME/bin:$ANT_HOME/bin:$JAVA_HOME/bin:$syspath
```

I build with the command:

```ShellSession
ubuntu@openjfx:~/src/jfx$ gradle -PCOMPILE_TARGETS=armv6hf
```

[1]: https://wiki.openjdk.java.net/display/OpenJFX/Cross+Building+for+ARM+Hard+Float

**Comment by johanvos** [comment]
Let's discuss the build procedures offline. In case some changes are needed, we can file a new issue for this.
